version: "3"

services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  app:
    build: .
    depends_on:
      - mongo
    command: java -jar /usr/local/lib/simian-api.jar
    ports:
      - "80:80"